import Navbar from "@/components/navbar/Navbar";
import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import LeftSidebar from "@/components/navbar/LeftSidebar";
import { EdgeStoreProvider } from "@/libs/edgestore";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <main className="flex bg-gradient-to-r from-black to-purple-500 text-gray-200">
            <LeftSidebar />
            <EdgeStoreProvider>{children}</EdgeStoreProvider>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
